// Все категории и товары доната DewtoWorld
export const donationCategories = [
  {
    id: 'privileges',
    name: 'Привилегии',
    items: [
      {
        name: 'Герой',
        price: 250,
        features: [
          'Префикс [Герой] в чате',
          'Доступ к /fly и /ec',
          'Набор предметов',
          '5 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Страж',
        price: 400,
        features: [
          'Префикс [Страж] в чате',
          'Доступ к /fly, /ec и /ptime',
          'Набор стража',
          '10 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Шторм',
        price: 600,
        features: [
          'Префикс [Шторм] в чате',
          'Доступ к /fly, /ec и /ptime',
          'Набор шторма',
          '15 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Лорд',
        price: 800,
        features: [
          'Префикс [Лорд] в чате',
          'Доступ ко всем командам',
          'Набор лорда',
          '25 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Разоритель',
        price: 1000,
        features: [
          'Префикс [Разоритель]',
          'Доступ ко всем командам',
          'Набор разорителя',
          '30 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Император',
        price: 1500,
        features: [
          'Префикс [Император]',
          'Доступ ко всем командам',
          'Набор императора',
          '40 слотов /home',
        ],
        popular: true,
        label: 'ПОПУЛЯРНЫЙ',
      },
      {
        name: 'Лето',
        price: 1800,
        features: [
          'Префикс [Лето]',
          'Доступ ко всем командам',
          'Набор лета',
          '50 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Визер',
        price: 2200,
        features: [
          'Префикс [Визер]',
          'Доступ ко всем командам',
          'Набор визера',
          '60 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Хранитель',
        price: 2600,
        features: [
          'Префикс [Хранитель]',
          'Доступ ко всем командам',
          'Набор хранителя',
          '70 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Зевс',
        price: 3000,
        features: [
          'Префикс [Зевс]',
          'Доступ ко всем командам',
          'Набор Зевса',
          '80 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Рубик',
        price: 3500,
        features: [
          'Префикс [Рубик]',
          'Доступ ко всем командам',
          'Набор Рубика',
          '90 слотов /home',
        ],
        popular: false,
      },
      {
        name: 'Аристократ',
        price: 5000,
        features: [
          'Префикс [Аристократ]',
          'Доступ ко всем командам',
          'Набор Аристократа',
          '100 слотов /home',
        ],
        popular: true,
        label: 'VIP',
      },
    ],
  },
  {
    id: 'currency',
    name: 'Рубины',
    items: [
      { name: 'Рубины', amount: 500, price: 50 },
      { name: 'Рубины', amount: 1000, price: 100 },
      { name: 'Рубины', amount: 3000, price: 250 },
      { name: 'Рубины', amount: 6000, price: 450 },
      { name: 'Рубины', amount: 8000, price: 600 },
      { name: 'Рубины', amount: 16000, price: 1000 },
    ],
  },
  {
    id: 'keys',
    name: 'Ключи',
    items: [
      {
        name: 'Мега Донат кейс',
        price: 150,
        description: 'Эксклюзивный набор с редкими предметами и ресурсами',
        icon: 'gem',
      },
      {
        name: 'Донат кейс',
        price: 75,
        description: 'Стандартный набор с полезными предметами',
        icon: 'box-open',
      },
      {
        name: 'Мега рубиновый кейс',
        price: 200,
        description: 'Большое количество рубинов и эксклюзивные предметы',
        icon: 'diamond',
      },
      {
        name: 'Кейс с рубинами',
        price: 100,
        description: 'Набор рубинов для покупки внутриигровых товаров',
        icon: 'coins',
      },
      {
        name: 'Кейс с китами',
        price: 180,
        description: 'Эксклюзивные питомцы и морские ресурсы',
        icon: 'fish',
      },
      {
        name: 'Кейс с титулами',
        price: 120,
        description: 'Уникальные титулы и префиксы для вашего персонажа',
        icon: 'crown',
      },
    ],
  },
  {
    id: 'misc',
    name: 'Разное',
    items: [
      {
        name: 'Поддержка проекта',
        price: 1,
        description: 'Символическая поддержка сервера. Ваш вклад помогает развитию проекта!',
        icon: 'heart',
        button: 'Поддержать',
      },
      {
        name: 'Подписка DW+',
        price: 299,
        description: 'Ежемесячная подписка с эксклюзивными бонусами и привилегиями',
        icon: 'star',
        button: 'Оформить',
        monthly: true,
      },
      {
        name: 'Размут',
        price: 150,
        description: 'Снятие ограничения на отправку сообщений в чате',
        icon: 'comment-slash',
      },
      {
        name: 'Разбан',
        price: 500,
        description: 'Снятие блокировки с вашего аккаунта после нарушения правил',
        icon: 'ban',
      },
    ],
  },
]
